### ISSUE TITLE
Love button not working when clicked show error `Post id is required`

### ISSUE THREAD

**Issue by divyanshugarg36** [BRL-CAD/OGV-meteor#121]
![Peek 2022-03-26 23-16](https://user-images.githubusercontent.com/37038354/160252000-30dce242-400c-4809-a94c-5e2980a6ec6b.gif)

**Comment by divyanshugarg36** [comment]
https://github.com/BRL-CAD/OGV-meteor/pull/122

**Comment by drossberg** [comment]
Fixed with #122
