### ISSUE TITLE
Meteor admin user creation

### ISSUE THREAD

**Issue by inderpreetsingh** [BRL-CAD/OGV-meteor#53]
If you run meteor without properly writing config.json. Default admin user is created without any password. 

We would also like the default admin password be generated randomly and shown in server console rather than `your_password_here`

**Comment by ditttu** [comment]
I would like to work on this. Please assign this to me.

**Comment by Gauravjeetsingh** [comment]
There you go @ditttu. Thank you for informing. Keep us updated with the progress.

**Comment by Max2020q** [comment]
https://github.com/BRL-CAD/OGV-meteor/pull/91

**Comment by Max2020q** [comment]
Fixed with new commit
