### ISSUE TITLE
CSS code improvement [Code Quality]

### ISSUE THREAD

**Issue by inderpreetsingh** [BRL-CAD/OGV-meteor#58]
All of the current CSS code is one file. Divide it into multiple files and improve the code quality.

Discus possible porting to scss.

**Comment by Max2020q** [comment]
I am investing a lot more time into researching possible solutions within the project now that finals are completed.

I believe SCSS could possibly allow for the styling to naturally be more dynamic and inherently give more interface customization to the user through SCSS version of mixins and variables.

**Comment by inderpreetsingh** [comment]
@Max2020q  I like your idea. We should discuss this after you have researched before moving forward. Let me know and we can schedule a call or a chat.

**Comment by rathod-sahaab** [comment]
However, splitting into multiple files would increase network latency.
see [this article](https://medium.com/netscape/cut-your-web-applications-load-time-in-half-with-these-webpack-optimization-techniques-e9f92dbaab4e)

The solution for this would be to bundle using bundlers like **webpack**.
which I made a configuration of [here](https://github.com/rathod-sahaab/webpack-pug-less-babel),

Which was used in [this single page webappp](https://github.com/istenith/prodyogiki)

**Comment by drossberg** [comment]
Done with #111 / 7295da160d37f5d5e01ddf722d80fc520eb73d9d .
