### ISSUE TITLE
Bring custom coloring back

### ISSUE THREAD

**Issue by inderpreetsingh** [BRL-CAD/OGV-meteor#67]
OGV used to have custom coloring panel which was removed when we chose to add colors directly from .g file. However, as we also allow upload of single obj files it's worth allowing the user to change colors of different parts if he/she wants.

**Comment by Max2020q** [comment]
This is an extremely interesting feature and can be pushed further to feature gradients and more complexity as well.

Will definitely look into this to see how to create a good color picker user experience.

**Comment by drossberg** [comment]
Fixed with #113 / 2effd7c3c48bf3f692716a4c5b96bca41930c11f
