### ISSUE TITLE
Port three.js to its latest version.

### ISSUE THREAD

**Issue by inderpreetsingh** [BRL-CAD/OGV-meteor#70]

**Comment by Max2020q** [comment]
Greetings! My name is Quentin Paden and I'm a student at Georgia State University.

I am very proud of the hard work put into OGV for the 3D industry and would like to help continue improve it.

I have a background with Three.js and UI development with games in C#. I can help resolve issues that may arise when porting and upgrading to R103 .
(https://github.com/mrdoob/three.js/releases)

I will be submitting a PR for this issue and will try to upgrade meteor as well before submitting a proposal. This project is exciting!

**Comment by Gauravjeetsingh** [comment]
Hey @Max2020q, Glad to hear about your experience with three.js It will be really beneficial for OGV.

Just keep in mind that the final deadline for putting up a proposal in GSoC is 9th April. I would suggest you to start working on writing your proposal as well. We won't be able to consider your application if there's no proposal before the deadline.

**Comment by Max2020q** [comment]
Greetings @Gauravjeetsingh! It's nice to meet you all and help out. I am very familiar with Three.js, 3D software, and UI development with CSS, HTML, and a lot of Javascript 👍  

With Three.js r103, I really believe the variety of easy to set up Three.js Object Loaders, Coloring Systems, and Texturing Systems available within the new documentation will allow this project to become a useful utility in the future for designers! I am excited to continue to contribute. 

I have submitted my proposal and application for GSoC and I would definately like to keep in touch about the potential implementations for coloring models with Three.js and responsive UI development.

**Comment by Max2020q** [comment]
Hello I have solved this issue, I would like to close it, I can update Three.js again to r105, since this update they have updated to r105 with new lightmapping features.

https://github.com/mrdoob/three.js/releases

**Comment by Max2020q** [comment]
Would like to close now that this is merged https://github.com/BRL-CAD/OGV-meteor/pull/88
